/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Arion Digital (https://sketchfab.com/andrewswihart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-truck-1f5174e78fd549a8be8f7ae622caa223
Title: Cyber Truck
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CyberTruck(props) {
  const { nodes, materials } = useGLTF("/cyber_truck.glb");
  return (
    <group {...props} castShadow={true} receiveShadow={true} dispose={null}>
      <group position={[-5, -0.5, 5]} rotation={[0, 0.45, 0]} scale={0.02}>
        <group position={[0, 0, 0]}>
          <mesh
            geometry={nodes.updated_tire001_Tire_0.geometry}
            material={materials.Tire}
          />
          <mesh
            geometry={nodes.updated_tire001_Rims_0.geometry}
            material={materials.Rims}
          />
          <mesh
            geometry={nodes.updated_tire001_Undercarag_0.geometry}
            material={materials.Undercarag}
          />
          <mesh
            geometry={nodes.updated_tire001_Body_0.geometry}
            material={materials.Body}
          />
          <mesh
            geometry={nodes.updated_tire001_Headlights_0.geometry}
            material={materials.Headlights}
          />
          <mesh
            geometry={nodes.updated_tire001_Glass_0.geometry}
            material={materials.Glass}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
